/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: React Summit 2023
 * Environment: Production
 * Project Id: 55d82122-5c74-014e-1c44-9ac57c335706
 */
export const assetFolders = {} as const;
