/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: React Summit 2023
 * Environment: Production
 * Project Id: 55d82122-5c74-014e-1c44-9ac57c335706
 */
export const contentTypes = {
  /**
   * [Component] CTA
   */
  _component__cta: {
    codename: '_component__cta',
    id: '0c8e8dcf-351c-4982-8b70-cd43efe97b63',
    externalId: undefined,
    name: '[Component] CTA',
    elements: {
      /**
       * Text (text)
       */
      text: {
        codename: 'text',
        id: '017ce41d-5ef0-4b72-87f9-c99330ab6984',
        externalId: undefined,
        name: 'Text',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * URL (text)
       */
      url: {
        codename: 'url',
        id: 'ad9b5263-fa97-4f76-a409-7f7fc7dd9baa',
        externalId: undefined,
        name: 'URL',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * [Component] Hero
   */
  component_hero: {
    codename: 'component_hero',
    id: '86b210c1-7723-4b7b-9e0b-5d5b22d65151',
    externalId: undefined,
    name: '[Component] Hero',
    elements: {
      /**
       * Cards (modular_content)
       */
      cards: {
        codename: 'cards',
        id: '19e97d0b-8207-46d3-a350-4a8bb15a2d57',
        externalId: undefined,
        name: 'Cards',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Video (asset)
       */
      video: {
        codename: 'video',
        id: 'c791045d-1fa7-4bb0-8c52-1b20674a97be',
        externalId: undefined,
        name: 'Video',
        required: true,
        type: 'asset',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * [Component] Listing
   */
  component_listing: {
    codename: 'component_listing',
    id: 'ccdda5d4-422f-4e16-b59a-7c56205c5c9d',
    externalId: undefined,
    name: '[Component] Listing',
    elements: {
      /**
       * Data (modular_content)
       */
      data: {
        codename: 'data',
        id: '0e8558fd-056c-4253-b38f-39553ebb2217',
        externalId: undefined,
        name: 'Data',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: 'bca9ec45-a7a1-49c7-aef4-f3a0db34010c',
        externalId: undefined,
        name: 'Title',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * [Component] Newsletter CTA
   */
  component_newsletter_cta: {
    codename: 'component_newsletter_cta',
    id: 'a10d66f1-0abc-487a-bcd1-abf946f21966',
    externalId: undefined,
    name: '[Component] Newsletter CTA',
    elements: {},
  },

  /**
   * [Component] Text Section
   */
  component_text_section: {
    codename: 'component_text_section',
    id: '55315ad4-7cb8-4355-b475-241b5b1814e0',
    externalId: undefined,
    name: '[Component] Text Section',
    elements: {
      /**
       * Text (rich_text)
       */
      text: {
        codename: 'text',
        id: 'fac58edd-83a6-464e-a0a3-3a9e5f31181d',
        externalId: undefined,
        name: 'Text',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: 'b78c51f7-8585-4bfd-a274-b45f184df99c',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Aircraft
   */
  aircraft: {
    codename: 'aircraft',
    id: '23b729d0-483d-4097-9704-1a82f05b0273',
    externalId: undefined,
    name: 'Aircraft',
    elements: {
      /**
       * ID (text)
       */
      id: {
        codename: 'id',
        id: '71bbc124-0ec4-4d9b-a08a-e31c57ad1528',
        externalId: undefined,
        name: 'ID',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Type (multiple_choice)
       */
      type: {
        codename: 'type',
        id: '3283e8cb-d8b6-4f5d-96e5-c0b132744315',
        externalId: undefined,
        name: 'Type',
        required: false,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Airport
   */
  airport: {
    codename: 'airport',
    id: 'dd3ccd79-1c58-4a6d-b662-baf8fb194194',
    externalId: undefined,
    name: 'Airport',
    elements: {
      /**
       * Code (text)
       */
      code: {
        codename: 'code',
        id: 'a0200c39-709b-4cd1-967b-8b9ee5e02691',
        externalId: undefined,
        name: 'Code',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: 'a323f070-bb72-470c-a060-8940deafdf64',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Destination
   */
  destination: {
    codename: 'destination',
    id: '209e2cfc-d731-4cd3-9b43-bf13a7c54bd4',
    externalId: undefined,
    name: 'Destination',
    elements: {
      /**
       * Photo (asset)
       */
      photo: {
        codename: 'photo',
        id: 'db5e280f-e292-44bd-9601-099714b1a7bb',
        externalId: undefined,
        name: 'Photo',
        required: true,
        type: 'asset',
        snippetCodename: undefined,
      },

      /**
       * Text (rich_text)
       */
      text: {
        codename: 'text',
        id: 'fd1644e6-bcd6-4e37-ad71-ce5f591b7296',
        externalId: undefined,
        name: 'Text',
        required: true,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '4feabff5-748a-46d6-a5a3-38ee529d5192',
        externalId: undefined,
        name: 'Title',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Flight
   */
  flight: {
    codename: 'flight',
    id: 'e93a6414-4612-478a-ad3d-8f65ebf9dacf',
    externalId: undefined,
    name: 'Flight',
    elements: {
      /**
       * Aircraft (modular_content)
       */
      aircraft: {
        codename: 'aircraft',
        id: '6f4dae62-b33c-408a-a97b-1bf1f7af09e7',
        externalId: undefined,
        name: 'Aircraft',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Arrival (date_time)
       */
      arrival: {
        codename: 'arrival',
        id: 'ad9bee97-6ff7-495f-94fb-a81f5445c36f',
        externalId: undefined,
        name: 'Arrival',
        required: true,
        type: 'date_time',
        snippetCodename: undefined,
      },

      /**
       * Departure (date_time)
       */
      departure: {
        codename: 'departure',
        id: 'b5d29750-d1dc-456e-9d00-cc1a102e4930',
        externalId: undefined,
        name: 'Departure',
        required: true,
        type: 'date_time',
        snippetCodename: undefined,
      },

      /**
       * Destination (modular_content)
       */
      destination: {
        codename: 'destination',
        id: '4b81b576-9f50-4d28-b2ed-4b5bed158985',
        externalId: undefined,
        name: 'Destination',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Origin (modular_content)
       */
      origin: {
        codename: 'origin',
        id: 'cd39faa0-ea20-4cb3-afa1-cefe6e78cdd8',
        externalId: undefined,
        name: 'Origin',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Statuses (modular_content)
       */
      statuses: {
        codename: 'statuses',
        id: 'ca39da6d-2ed5-4e7a-b091-13c7f65b7108',
        externalId: undefined,
        name: 'Statuses',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Hero Card
   */
  hero_card: {
    codename: 'hero_card',
    id: '0e611f4a-5b48-496a-8414-86b4be0f1cfd',
    externalId: undefined,
    name: 'Hero Card',
    elements: {
      /**
       * Text (rich_text)
       */
      text: {
        codename: 'text',
        id: 'a2f5ecb2-0516-4a3f-a57c-ce8e8892ba49',
        externalId: undefined,
        name: 'Text',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: 'fa0087f7-205f-45e7-915b-704858cccac7',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Status
   */
  status: {
    codename: 'status',
    id: '8f562b45-680b-4284-8a98-e355d48f7177',
    externalId: undefined,
    name: 'Status',
    elements: {
      /**
       * Message (text)
       */
      message: {
        codename: 'message',
        id: '4991f4a5-fc78-4a75-8d4b-561d092545de',
        externalId: undefined,
        name: 'Message',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Severity (multiple_choice)
       */
      severity: {
        codename: 'severity',
        id: '6758c70d-fac2-4624-a81c-9b03f5f93257',
        externalId: undefined,
        name: 'Severity',
        required: false,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },
    },
  },
} as const;
