/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Reactathon demo
 * Environment: Production
 * Project Id: 10909e88-fc9f-01cd-787b-068c4c4a06f1
 */
export const contentTypes = {
  /**
   * [Component] CTA
   */
  _component__cta: {
    codename: '_component__cta',
    id: '78038470-3495-4fbf-af66-3babea85de14',
    externalId: undefined,
    name: '[Component] CTA',
    elements: {
      /**
       * Text (text)
       */
      text: {
        codename: 'text',
        id: '4c211daa-df4b-4b81-bf7d-7e882d41a363',
        externalId: undefined,
        name: 'Text',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * URL (text)
       */
      url: {
        codename: 'url',
        id: '41bb0a6d-d57f-4422-9f11-29aa4a7631b1',
        externalId: undefined,
        name: 'URL',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * [Component] Hero
   */
  component_hero: {
    codename: 'component_hero',
    id: '95f0e103-e3f8-4b5d-a709-36b087cc2e66',
    externalId: undefined,
    name: '[Component] Hero',
    elements: {
      /**
       * Cards (modular_content)
       */
      cards: {
        codename: 'cards',
        id: '73805ea1-c2df-4859-bbf6-617a5169c7b9',
        externalId: undefined,
        name: 'Cards',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Video (asset)
       */
      video: {
        codename: 'video',
        id: '9aa08431-5609-49c4-bd5b-ec39a9816db6',
        externalId: undefined,
        name: 'Video',
        required: true,
        type: 'asset',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * [Component] Listing
   */
  component_listing: {
    codename: 'component_listing',
    id: '13005a37-f1fd-49a2-b8aa-241337ac7ce3',
    externalId: undefined,
    name: '[Component] Listing',
    elements: {
      /**
       * Data (modular_content)
       */
      data: {
        codename: 'data',
        id: '74508578-7933-4d65-b670-ecb01c448939',
        externalId: undefined,
        name: 'Data',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '2ff7133d-8c50-4f60-b4a1-00f7cc33059c',
        externalId: undefined,
        name: 'Title',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * [Component] Newsletter CTA
   */
  component_newsletter_cta: {
    codename: 'component_newsletter_cta',
    id: 'eb2b71b8-e64a-4795-8268-a17e71ebec60',
    externalId: undefined,
    name: '[Component] Newsletter CTA',
    elements: {},
  },

  /**
   * [Component] Text Section
   */
  component_text_section: {
    codename: 'component_text_section',
    id: '1acd9f53-677f-4880-991d-3d6d1542926e',
    externalId: undefined,
    name: '[Component] Text Section',
    elements: {
      /**
       * Text (rich_text)
       */
      text: {
        codename: 'text',
        id: '74ce0ffe-0740-4b5e-89d0-6b66af81c3ec',
        externalId: undefined,
        name: 'Text',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '888d9eab-d1f6-4319-a8fd-7e63901e9404',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Aircraft
   */
  aircraft: {
    codename: 'aircraft',
    id: '8cbe7938-cfab-4de4-8b90-12fd03870d5a',
    externalId: undefined,
    name: 'Aircraft',
    elements: {
      /**
       * ID (text)
       */
      id: {
        codename: 'id',
        id: 'c60c290c-ed59-4e80-8661-5e1116f19d1e',
        externalId: undefined,
        name: 'ID',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Type (multiple_choice)
       */
      type: {
        codename: 'type',
        id: 'ba496f66-2f98-4300-8e4d-1528e4a3c688',
        externalId: undefined,
        name: 'Type',
        required: false,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Airport
   */
  airport: {
    codename: 'airport',
    id: '949bcc8d-e94b-49a8-b3e4-9ad82116cfbc',
    externalId: undefined,
    name: 'Airport',
    elements: {
      /**
       * Code (text)
       */
      code: {
        codename: 'code',
        id: 'cc9288e4-ea96-4e6e-ae2f-7faad556d546',
        externalId: undefined,
        name: 'Code',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '03ba4fe9-7ec9-4cd5-9466-eaa6733aa5bb',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Destination
   */
  destination: {
    codename: 'destination',
    id: 'e7f79325-38ae-43ec-9f91-61a41d03c35c',
    externalId: undefined,
    name: 'Destination',
    elements: {
      /**
       * Photo (asset)
       */
      photo: {
        codename: 'photo',
        id: '7a30035d-e04e-4357-bb74-66340d5b0dce',
        externalId: undefined,
        name: 'Photo',
        required: true,
        type: 'asset',
        snippetCodename: undefined,
      },

      /**
       * Text (rich_text)
       */
      text: {
        codename: 'text',
        id: '16b5e7bb-1150-4052-9c18-30ce9ab024e1',
        externalId: undefined,
        name: 'Text',
        required: true,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '85e222a5-f936-470b-9d9d-40b2f72d1f65',
        externalId: undefined,
        name: 'Title',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Flight
   */
  flight: {
    codename: 'flight',
    id: '6313eb4a-f745-4fc4-9131-3873fd84d504',
    externalId: undefined,
    name: 'Flight',
    elements: {
      /**
       * Aircraft (modular_content)
       */
      aircraft: {
        codename: 'aircraft',
        id: 'deacd4a5-bd2d-4a2a-9ba6-2661a140d21d',
        externalId: undefined,
        name: 'Aircraft',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Arrival (date_time)
       */
      arrival: {
        codename: 'arrival',
        id: '20cc6422-330d-480c-8cbc-b8af70c79ca9',
        externalId: undefined,
        name: 'Arrival',
        required: true,
        type: 'date_time',
        snippetCodename: undefined,
      },

      /**
       * Departure (date_time)
       */
      departure: {
        codename: 'departure',
        id: 'd7973639-964a-4f4e-ab99-310d0ad3fdf2',
        externalId: undefined,
        name: 'Departure',
        required: true,
        type: 'date_time',
        snippetCodename: undefined,
      },

      /**
       * Destination (modular_content)
       */
      destination: {
        codename: 'destination',
        id: '0b2e5e07-1684-41be-b844-fdf626ed017c',
        externalId: undefined,
        name: 'Destination',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Origin (modular_content)
       */
      origin: {
        codename: 'origin',
        id: '76d1985f-a8fe-4245-bc80-3a496d625917',
        externalId: undefined,
        name: 'Origin',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Statuses (modular_content)
       */
      statuses: {
        codename: 'statuses',
        id: 'ee81ec04-ff93-452a-8532-a0712894700b',
        externalId: undefined,
        name: 'Statuses',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Hero Card
   */
  hero_card: {
    codename: 'hero_card',
    id: 'd309e071-8a63-4567-86ac-5d3263a2ad6f',
    externalId: undefined,
    name: 'Hero Card',
    elements: {
      /**
       * Text (rich_text)
       */
      text: {
        codename: 'text',
        id: 'b77a7912-be70-4873-8ac1-e6329d3ad852',
        externalId: undefined,
        name: 'Text',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: 'f3e81353-6eb5-4ae7-975a-3fe342eceacd',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Status
   */
  status: {
    codename: 'status',
    id: '6c1b56d5-75ff-4e4c-ad28-ad43ae88d09a',
    externalId: undefined,
    name: 'Status',
    elements: {
      /**
       * Message (text)
       */
      message: {
        codename: 'message',
        id: '5eebd87c-ae61-4a37-b9bc-fe6fcc879ff2',
        externalId: undefined,
        name: 'Message',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Severity (multiple_choice)
       */
      severity: {
        codename: 'severity',
        id: '42f59aee-2cbd-4a99-86ef-bda05464102e',
        externalId: undefined,
        name: 'Severity',
        required: false,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },
    },
  },
} as const;
