/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Reactathon demo
 * Environment: Production
 * Project Id: 10909e88-fc9f-01cd-787b-068c4c4a06f1
 */
export const roles = {} as const;
