import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Aircraft
 * Id: 23b729d0-483d-4097-9704-1a82f05b0273
 * Codename: aircraft
 */
export type AircraftModel = IContentItem<{
  /**
   * ID (text)
   * Required: false
   * Id: 71bbc124-0ec4-4d9b-a08a-e31c57ad1528
   * Codename: id
   */
  id: Elements.TextElement;

  /**
   * Type (multiple_choice)
   * Required: false
   * Id: 3283e8cb-d8b6-4f5d-96e5-c0b132744315
   * Codename: type
   */
  type: Elements.MultipleChoiceElement;
}>;
