import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Airport
 * Id: dd3ccd79-1c58-4a6d-b662-baf8fb194194
 * Codename: airport
 */
export type AirportModel = IContentItem<{
  /**
   * Code (text)
   * Required: false
   * Id: a0200c39-709b-4cd1-967b-8b9ee5e02691
   * Codename: code
   */
  code: Elements.TextElement;

  /**
   * Title (text)
   * Required: false
   * Id: a323f070-bb72-470c-a060-8940deafdf64
   * Codename: title
   */
  title: Elements.TextElement;
}>;
