import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Airport
 * Id: 949bcc8d-e94b-49a8-b3e4-9ad82116cfbc
 * Codename: airport
 */
export type AirportModel = IContentItem<{
  /**
   * Code (text)
   * Required: false
   * Id: cc9288e4-ea96-4e6e-ae2f-7faad556d546
   * Codename: code
   */
  code: Elements.TextElement;

  /**
   * Title (text)
   * Required: false
   * Id: 03ba4fe9-7ec9-4cd5-9466-eaa6733aa5bb
   * Codename: title
   */
  title: Elements.TextElement;
}>;
