import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type HeroCardModel } from './HeroCardModel';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * [Component] Hero
 * Id: 86b210c1-7723-4b7b-9e0b-5d5b22d65151
 * Codename: component_hero
 */
export type ComponentHeroModel = IContentItem<{
  /**
   * Cards (modular_content)
   * Required: true
   * Id: 19e97d0b-8207-46d3-a350-4a8bb15a2d57
   * Codename: cards
   */
  cards: Elements.LinkedItemsElement<HeroCardModel>;

  /**
   * Video (asset)
   * Required: true
   * Id: c791045d-1fa7-4bb0-8c52-1b20674a97be
   * Codename: video
   */
  video: Elements.AssetsElement;
}>;
