import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type DestinationModel } from './DestinationModel';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * [Component] Listing
 * Id: 13005a37-f1fd-49a2-b8aa-241337ac7ce3
 * Codename: component_listing
 */
export type ComponentListingModel = IContentItem<{
  /**
   * Data (modular_content)
   * Required: true
   * Id: 74508578-7933-4d65-b670-ecb01c448939
   * Codename: data
   */
  data: Elements.LinkedItemsElement<DestinationModel>;

  /**
   * Title (text)
   * Required: true
   * Id: 2ff7133d-8c50-4f60-b4a1-00f7cc33059c
   * Codename: title
   */
  title: Elements.TextElement;
}>;
