import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type HeroCardModel } from './HeroCardModel';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * [Component] Hero
 * Id: 95f0e103-e3f8-4b5d-a709-36b087cc2e66
 * Codename: component_hero
 */
export type ComponentHeroModel = IContentItem<{
  /**
   * Cards (modular_content)
   * Required: true
   * Id: 73805ea1-c2df-4859-bbf6-617a5169c7b9
   * Codename: cards
   */
  cards: Elements.LinkedItemsElement<HeroCardModel>;

  /**
   * Video (asset)
   * Required: true
   * Id: 9aa08431-5609-49c4-bd5b-ec39a9816db6
   * Codename: video
   */
  video: Elements.AssetsElement;
}>;
