import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * [Component] Text Section
 * Id: 55315ad4-7cb8-4355-b475-241b5b1814e0
 * Codename: component_text_section
 */
export type ComponentTextSectionModel = IContentItem<{
  /**
   * Text (rich_text)
   * Required: false
   * Id: fac58edd-83a6-464e-a0a3-3a9e5f31181d
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Title (text)
   * Required: false
   * Id: b78c51f7-8585-4bfd-a274-b45f184df99c
   * Codename: title
   */
  title: Elements.TextElement;
}>;
