import { type IContentItem } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * [Component] Newsletter CTA
 * Id: eb2b71b8-e64a-4795-8268-a17e71ebec60
 * Codename: component_newsletter_cta
 */
export type ComponentNewsletterCtaModel = IContentItem<{}>;
