import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * [Component] CTA
 * Id: 78038470-3495-4fbf-af66-3babea85de14
 * Codename: _component__cta
 */
export type ComponentCtaModel = IContentItem<{
  /**
   * Text (text)
   * Required: true
   * Id: 4c211daa-df4b-4b81-bf7d-7e882d41a363
   * Codename: text
   */
  text: Elements.TextElement;

  /**
   * URL (text)
   * Required: true
   * Id: 41bb0a6d-d57f-4422-9f11-29aa4a7631b1
   * Codename: url
   */
  url: Elements.TextElement;
}>;
