import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type DestinationModel } from './DestinationModel';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * [Component] Listing
 * Id: ccdda5d4-422f-4e16-b59a-7c56205c5c9d
 * Codename: component_listing
 */
export type ComponentListingModel = IContentItem<{
  /**
   * Data (modular_content)
   * Required: true
   * Id: 0e8558fd-056c-4253-b38f-39553ebb2217
   * Codename: data
   */
  data: Elements.LinkedItemsElement<DestinationModel>;

  /**
   * Title (text)
   * Required: true
   * Id: bca9ec45-a7a1-49c7-aef4-f3a0db34010c
   * Codename: title
   */
  title: Elements.TextElement;
}>;
