import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * [Component] CTA
 * Id: 0c8e8dcf-351c-4982-8b70-cd43efe97b63
 * Codename: _component__cta
 */
export type ComponentCtaModel = IContentItem<{
  /**
   * Text (text)
   * Required: true
   * Id: 017ce41d-5ef0-4b72-87f9-c99330ab6984
   * Codename: text
   */
  text: Elements.TextElement;

  /**
   * URL (text)
   * Required: true
   * Id: ad9b5263-fa97-4f76-a409-7f7fc7dd9baa
   * Codename: url
   */
  url: Elements.TextElement;
}>;
