import { type IContentItem } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * [Component] Newsletter CTA
 * Id: a10d66f1-0abc-487a-bcd1-abf946f21966
 * Codename: component_newsletter_cta
 */
export type ComponentNewsletterCtaModel = IContentItem<{}>;
