import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * [Component] Text Section
 * Id: 1acd9f53-677f-4880-991d-3d6d1542926e
 * Codename: component_text_section
 */
export type ComponentTextSectionModel = IContentItem<{
  /**
   * Text (rich_text)
   * Required: false
   * Id: 74ce0ffe-0740-4b5e-89d0-6b66af81c3ec
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Title (text)
   * Required: false
   * Id: 888d9eab-d1f6-4319-a8fd-7e63901e9404
   * Codename: title
   */
  title: Elements.TextElement;
}>;
