import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Destination
 * Id: e7f79325-38ae-43ec-9f91-61a41d03c35c
 * Codename: destination
 */
export type DestinationModel = IContentItem<{
  /**
   * Photo (asset)
   * Required: true
   * Id: 7a30035d-e04e-4357-bb74-66340d5b0dce
   * Codename: photo
   */
  photo: Elements.AssetsElement;

  /**
   * Text (rich_text)
   * Required: true
   * Id: 16b5e7bb-1150-4052-9c18-30ce9ab024e1
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Title (text)
   * Required: true
   * Id: 85e222a5-f936-470b-9d9d-40b2f72d1f65
   * Codename: title
   */
  title: Elements.TextElement;
}>;
