import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Destination
 * Id: 209e2cfc-d731-4cd3-9b43-bf13a7c54bd4
 * Codename: destination
 */
export type DestinationModel = IContentItem<{
  /**
   * Photo (asset)
   * Required: true
   * Id: db5e280f-e292-44bd-9601-099714b1a7bb
   * Codename: photo
   */
  photo: Elements.AssetsElement;

  /**
   * Text (rich_text)
   * Required: true
   * Id: fd1644e6-bcd6-4e37-ad71-ce5f591b7296
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Title (text)
   * Required: true
   * Id: 4feabff5-748a-46d6-a5a3-38ee529d5192
   * Codename: title
   */
  title: Elements.TextElement;
}>;
