import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type AircraftModel } from './AircraftModel';
import { type AirportModel } from './AirportModel';
import { type StatusModel } from './StatusModel';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Flight
 * Id: 6313eb4a-f745-4fc4-9131-3873fd84d504
 * Codename: flight
 */
export type FlightModel = IContentItem<{
  /**
   * Aircraft (modular_content)
   * Required: true
   * Id: deacd4a5-bd2d-4a2a-9ba6-2661a140d21d
   * Codename: aircraft
   */
  aircraft: Elements.LinkedItemsElement<AircraftModel>;

  /**
   * Arrival (date_time)
   * Required: true
   * Id: 20cc6422-330d-480c-8cbc-b8af70c79ca9
   * Codename: arrival
   */
  arrival: Elements.DateTimeElement;

  /**
   * Departure (date_time)
   * Required: true
   * Id: d7973639-964a-4f4e-ab99-310d0ad3fdf2
   * Codename: departure
   */
  departure: Elements.DateTimeElement;

  /**
   * Destination (modular_content)
   * Required: true
   * Id: 0b2e5e07-1684-41be-b844-fdf626ed017c
   * Codename: destination
   */
  destination: Elements.LinkedItemsElement<AirportModel>;

  /**
   * Origin (modular_content)
   * Required: true
   * Id: 76d1985f-a8fe-4245-bc80-3a496d625917
   * Codename: origin
   */
  origin: Elements.LinkedItemsElement<AirportModel>;

  /**
   * Statuses (modular_content)
   * Required: false
   * Id: ee81ec04-ff93-452a-8532-a0712894700b
   * Codename: statuses
   */
  statuses: Elements.LinkedItemsElement<StatusModel>;
}>;
