import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type AircraftModel } from './AircraftModel';
import { type AirportModel } from './AirportModel';
import { type StatusModel } from './StatusModel';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Flight
 * Id: e93a6414-4612-478a-ad3d-8f65ebf9dacf
 * Codename: flight
 */
export type FlightModel = IContentItem<{
  /**
   * Aircraft (modular_content)
   * Required: true
   * Id: 6f4dae62-b33c-408a-a97b-1bf1f7af09e7
   * Codename: aircraft
   */
  aircraft: Elements.LinkedItemsElement<AircraftModel>;

  /**
   * Arrival (date_time)
   * Required: true
   * Id: ad9bee97-6ff7-495f-94fb-a81f5445c36f
   * Codename: arrival
   */
  arrival: Elements.DateTimeElement;

  /**
   * Departure (date_time)
   * Required: true
   * Id: b5d29750-d1dc-456e-9d00-cc1a102e4930
   * Codename: departure
   */
  departure: Elements.DateTimeElement;

  /**
   * Destination (modular_content)
   * Required: true
   * Id: 4b81b576-9f50-4d28-b2ed-4b5bed158985
   * Codename: destination
   */
  destination: Elements.LinkedItemsElement<AirportModel>;

  /**
   * Origin (modular_content)
   * Required: true
   * Id: cd39faa0-ea20-4cb3-afa1-cefe6e78cdd8
   * Codename: origin
   */
  origin: Elements.LinkedItemsElement<AirportModel>;

  /**
   * Statuses (modular_content)
   * Required: false
   * Id: ca39da6d-2ed5-4e7a-b091-13c7f65b7108
   * Codename: statuses
   */
  statuses: Elements.LinkedItemsElement<StatusModel>;
}>;
