import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Hero Card
 * Id: 0e611f4a-5b48-496a-8414-86b4be0f1cfd
 * Codename: hero_card
 */
export type HeroCardModel = IContentItem<{
  /**
   * Text (rich_text)
   * Required: false
   * Id: a2f5ecb2-0516-4a3f-a57c-ce8e8892ba49
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Title (text)
   * Required: false
   * Id: fa0087f7-205f-45e7-915b-704858cccac7
   * Codename: title
   */
  title: Elements.TextElement;
}>;
