import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Status
 * Id: 8f562b45-680b-4284-8a98-e355d48f7177
 * Codename: status
 */
export type StatusModel = IContentItem<{
  /**
   * Message (text)
   * Required: false
   * Id: 4991f4a5-fc78-4a75-8d4b-561d092545de
   * Codename: message
   */
  message: Elements.TextElement;

  /**
   * Severity (multiple_choice)
   * Required: false
   * Id: 6758c70d-fac2-4624-a81c-9b03f5f93257
   * Codename: severity
   */
  severity: Elements.MultipleChoiceElement;
}>;
