import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Status
 * Id: 6c1b56d5-75ff-4e4c-ad28-ad43ae88d09a
 * Codename: status
 */
export type StatusModel = IContentItem<{
  /**
   * Message (text)
   * Required: false
   * Id: 5eebd87c-ae61-4a37-b9bc-fe6fcc879ff2
   * Codename: message
   */
  message: Elements.TextElement;

  /**
   * Severity (multiple_choice)
   * Required: false
   * Id: 42f59aee-2cbd-4a99-86ef-bda05464102e
   * Codename: severity
   */
  severity: Elements.MultipleChoiceElement;
}>;
